LOCAL_PATH := $(call my-dir)

#Bnotes
include $(CLEAR_VARS)
LOCAL_MODULE := BNotes
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SDK_VERSION := current
LOCAL_MIN_SDK_VERSION := 19
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_SRC_FILES := BNotes/bnotes.apk
include $(BUILD_PREBUILT)